#!/usr/bin/env python

import sys, math

def maxScore(codons, index):
    currentLow, currentHigh, currentScore = codons[index]
    sizes = [0]
    for i in xrange(index+1,len(codons)):
        low, high, score = codons[i]
        if (not currentLow <= low <= currentHigh) and (not currentLow <= high <= currentHigh):
            sizes += [maxScore(codons,i)]
    return currentScore + max(sizes)

def main(argv):
    fileName = argv[1]
    urFile = open(fileName)
    
    dnaLength = int(urFile.readline().strip())
    dnaLines = int(math.ceil(dnaLength / 80.0) + 1)
    
    upLines = urFile.readlines()[dnaLines:]
    
    codons = [[int(val) for val in line.strip().split()] for line in upLines if line]
    codons = sorted(codons, key=lambda code: code[0])
    codons = [(-1,-1,0)] + codons
    
    geneScore = maxScore(codons,0)
    
    sys.stdout.write('%s\n' % geneScore)

if __name__ == '__main__':
    main(sys.argv)
