#!/usr/bin/env python
import sys

with open(sys.argv[1]) as urFile:
    n = int(urFile.readline())
    for i in xrange(1, n + 1):
        if i % 3 == 0 and i % 5 == 0:
            sys.stdout.write('Hop\n')
        elif i % 3 == 0:
            sys.stdout.write('Hoppity\n')
        elif i % 5 == 0:
            sys.stdout.write('Hophop\n')
